@extends('user-interface.layout')
@extends('user-interface.partials.initial-meta')
@extends('user-interface.partials.header')
@extends('user-interface.partials.left-sidebar')
@extends('user-interface.partials.right-sidebar')
@extends('user-interface.catalog')
@extends('user-interface.partials.footer')
